// SISTEMA DE ENCUESTAS (Programación Orientada a Objetos)
// Pedimos el nombre de la empresa u organización al usuario
const nombreEmpresa = prompt("Hola, ingrese el nombre de la empresa u organizacion:");
alert("CONTINUA TODO POR CONSOLA (F-12)"); // Solo alerta, todo el manejo será por consola

// Mensaje de bienvenida
console.log("====================================");
console.log(" Plataforma de encuestas - Bienvenido");
console.log(" Empresa u Organizacion: " + nombreEmpresa);
console.log("====================================");